version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    environment:
      ConnectionStrings__Default: "User ID=postgres;Password=root;Host=dotnet_postgres;Port=5432;Database=RussianSpotify.API.Data"
    ports:
      - "80:80"
    networks:
      - dotnet_network
  
  dotnet_mailing:
    image: dotnet-web
    
  dotnet_storage:
    image: dotnet-web
    
    
volumes: 
  postgres_data:
    
networks:
  dotnet_network:
    driver: bridge